# Project: factorial
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib" -L"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/include" -I"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/include" -I"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/ProgramData/App-V/34795ABA-299A-40BB-A675-AC89576FB7E6/BAC9C63F-D38A-4534-9B42-AD8EDF811810/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = factorial.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
